import { z } from 'astro/zod';
export const technologies = ['autolisp', 'visual-lisp-activex', 'autocad-dotnet', 'civil3d-dotnet', 'dynamo-python', 'gis-data-automation'] as const;
export const technologySchema = z.enum(technologies);
export type Technology = z.infer<typeof technologySchema>;
export type ContentId = string;
export type CourseId = string;
export type ChapterId = string;
export type LessonId = string;
export type ConceptId = string;
export type ExampleId = string;
export type ExerciseId = string;
export type ProjectId = string;
const strings = z.array(z.string().trim().min(1)).default([]);
const difficulty = z.enum(['co-ban', 'trung-cap', 'nang-cao']);
const compatibility = z.array(z.object({ product: z.string(), version: z.string(), platform: z.string().optional() })).default([]);
const sources = z.array(z.object({ title: z.string().min(1), url: z.url() })).default([]);
const examplePlacements = z.array(z.object({ heading: z.string().min(1), exampleIds: z.array(z.string().startsWith('example.')).min(1) })).default([]);
const common = (prefix: string) => ({ id: z.string().regex(new RegExp(`^${prefix}\\.[a-z0-9.-]+$`)), slug: z.string().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/), title: z.string().trim().min(1), description: z.string().trim().min(1), status: z.enum(['draft', 'published']).default('draft'), tags: strings, aliases: strings, searchableTerms: strings });
export const courseSchema = z.object({ ...common('course'), technology: technologySchema, order: z.number().int().positive() });
export const chapterSchema = z.object({ ...common('chapter'), courseId: z.string().startsWith('course.'), order: z.number().int().positive() });
export const lessonSchema = z.object({ ...common('lesson'), chapterId: z.string().startsWith('chapter.'), order: z.number().int().positive(), difficulty, prerequisites: strings, conceptIds: strings, exampleIds: strings, examplePlacements, exerciseIds: strings, sources, compatibility });
export const conceptSchema = z.object({ ...common('concept'), technology: technologySchema, difficulty, kind: z.enum(['term', 'api', 'syntax', 'troubleshooting']), relatedConceptIds: strings, exampleIds: strings, examplePlacements, sources, compatibility });
export const exampleSchema = z.object({ ...common('example'), technology: technologySchema, language: z.enum(['lisp', 'csharp', 'python', 'json', 'xml', 'text']), sourceFile: z.string().min(1).refine(s => !s.split(/[\\/]/).includes('..') && !/^(?:[\\/]|[a-zA-Z]:)/.test(s), 'File code phải nằm trong examples/code.'), expectedOutput: z.string().optional(), compatibility, sources, verifiedWith: z.object({ product: z.string(), version: z.string(), platform: z.string(), checkedAt: z.iso.datetime() }).optional() });
export const exerciseSchema = z.object({ ...common('exercise'), technology: technologySchema, difficulty, expectedResult: z.string().min(1), solutionExampleId: z.string().optional(), conceptIds: strings, compatibility });
export const projectSchema = z.object({ ...common('project'), technology: technologySchema, difficulty, expectedResult: z.string().min(1), prerequisites: strings, conceptIds: strings, exampleIds: strings, examplePlacements, sources, compatibility });
export const schemas = { course: courseSchema, chapter: chapterSchema, lesson: lessonSchema, concept: conceptSchema, example: exampleSchema, exercise: exerciseSchema, project: projectSchema };
export type Entity = keyof typeof schemas;
type Entry<K extends Entity> = z.infer<(typeof schemas)[K]> & {
    entity: K;
    body?: string;
    file?: string;
};
export type CourseEntry = Entry<'course'>;
export type ChapterEntry = Entry<'chapter'>;
export type LessonEntry = Entry<'lesson'>;
export type ConceptEntry = Entry<'concept'>;
export type ExampleEntry = Entry<'example'>;
export type ExerciseEntry = Entry<'exercise'>;
export type ProjectEntry = Entry<'project'>;
export type ContentEntry = CourseEntry | ChapterEntry | LessonEntry | ConceptEntry | ExampleEntry | ExerciseEntry | ProjectEntry;
